---
# tasks file for nginx

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- import_tasks: configuration.yml