---
# tasks file for nginx

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Nginx version
  become: yes
  shell: |
   echo "[section]" > /etc/ansible/facts.d/nginx.fact
   nginx -v 2>> /etc/ansible/facts.d/nginx.fact
  changed_when: no

- import_tasks: configuration.yml
