---
# tasks file for user

- name: Include vars
  include_vars: users.yml

- name: Create user
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ users[username].password }}"
    uid: "{{ users[username].uid }}"
    
- name: Add to sudoers
  become: yes
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ username }}
  when:  users[username].privileges is defined