---
# tasks file for nexus

- name: Copy nexus.service
  become: yes
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
    owner: root
    group: root
    mode: 0644
  notify: daemon-reload
- meta: flush_handlers

- name: Download Nexus (local)
  become: yes
  copy:
    src: latest-unix.tar.gz
    dest: /home/nexus/

#- name: Download Nexus (internet)
#  get_url:
#    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
#    dest: /home/nexus
#    mode: 0666

- name: Check /opt/nexus
  stat:
    path: /opt/nexus
  register: result

- name: Unarchive nexus
  become: yes
  unarchive:
    src: /home/nexus/latest-unix.tar.gz
    dest: /opt/
    remote_src: yes
    owner: nexus
    group: nexus
  when: result.stat.exists == False
  notify: rename-nexus
- meta: flush_handlers

- name: Chown nexus dir
  become: yes
  file:
    path: /opt/nexus/
    owner: nexus
    group: nexus
    recurse: yes

- name: Chown sonatype-work dir
  become: yes
  file:
    path: /opt/sonatype-work/
    owner: nexus
    group: nexus
    recurse: yes

- name: Enable and start nexus
  become: yes
  systemd:
    enabled: yes
    state: started
    name: nexus

- name: Nexus version fact
  become: yes
  shell: |
   printf "[section]\nNexus_version=" > /etc/ansible/facts.d/nexus.fact
   curl --include --silent http://localhost:8081 | grep Server | awk {'print $2'} >> /etc/ansible/facts.d/nexus.fact
   sed -i ':a;2N;s/\n//g' /etc/ansible/facts.d/nexus.fact
  changed_when: no



#openssl passwd -salt <salt> -1 <plaintext>