---
# tasks file for jenkins

- name: Create /opt/jenkins/ directory
  file:
    path: /opt/jenkins/
    state: directory
    mode: 0755
    owner: jenkins
    group: jenkins

- name: Copy jenkins.war
  become: yes
  become_user: jenkins
  copy:
    src: jenkins.war
    dest: /opt/jenkins/

- name: Copy jenkins.service
  become: yes
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service

- name: Reload services
  become: yes
  systemd:
    daemon_reload: yes

- name: Make sure that jenkins.service is running
  systemd:
    state: started
    name: jenkins

- name: Jenkins version
  become: yes
  shell: |
   printf "[section]\nJenkins_version=" > /etc/ansible/facts.d/jenkins.fact
   head -5  /opt/jenkins/.jenkins/config.xml| grep -oP '(?<=<version>).*?(?=</version>)' >> /etc/ansible/facts.d/jenkins.fact
   sed -i ':a;2N;s/\n//g' /etc/ansible/facts.d/jenkins.fact
  changed_when: no


#java -Duser.home=/opt/jenkins -Xms1000m -Xmx1200m -jar /<path>/jenkins.war

#openssl passwd -salt <salt> -1 <plaintext>
